import Head from 'next/head'
import Navbar from '../components/Navbar'
import Main from '../components/Main'

export default function Home() {
  return (
    <div className='text-gray-700 font-body'>
      <Head>
        <title>Recipes for Ninja</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='grid md:grid-cols-3'>
        <Navbar/>
        <Main />
      </div>

    </div>
  )
}
